CREATE TABLE noticeboard (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(200) NOT NULL,
    notice VARCHAR(1500) NOT NULL,
    writer VARCHAR(1500) NOT NULL,
    timestampy DATETIME DEFAULT CURRENT_TIMESTAMP
);